name: Main
on: [push, pull_request]
jobs:
  test:
    name: Test all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.5.x"
          - "1.6.x"
          - "1.7.x"
          - "1.8.x"
          - "1.9.x"
          - "1.10.x"
          - "1.11.x"
          - "1.12.x"
          - "1.13.x"
          - "1.14.x"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1.0.2
        with:
          go-version: ${{matrix.go}}
        env:
          GOPATH: /home/runner # Fix for actions/setup-go@v1.0.2
      - name: Check out code
        uses: actions/checkout@v2.0.0
      - name: Get modules
        run: go get -v -t -d ./...
      - name: Test
        run: go test -v --coverprofile=cover.out ./...
      - name: Upload coverage profile
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: cover.out
